root_dir = "."
index_files = ["index.mdx"]
fallback_extensions = ["mdx"]
include_fragments = "anchor-only"
exclude_loopback = true
exclude = [
  "^https://canva\\.com/?$",
  "^https://console\\.mistral\\.ai/?$",
  "^https://platform\\.openai\\.com/?$",
]

remap = [
  "^file://(.*/docs.agent-one.dev)/docs/ file://$1/content/docs/",
  "^file://(.*/docs.agent-one.dev)/images/ file://$1/public/images/",
]
